version: "3"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444" # Exposes the Selenium Grid on port 4444
    environment:
      - GRID_MAX_SESSION=5 # Limit max sessions
      - GRID_BROWSER_TIMEOUT=60
      - GRID_TIMEOUT=30

  chrome:
    image: selenium/node-chrome:latest
    container_name: chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PORT=4442
      - SE_NODE_MAX_INSTANCES=2
      - SE_NODE_MAX_SESSIONS=5
    volumes:
      - /dev/shm:/dev/shm # For Chrome performance
    links:
      - selenium-hub

  firefox:
    image: selenium/node-firefox:latest
    container_name: firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PORT=4442
      - SE_NODE_MAX_INSTANCES=2
      - SE_NODE_MAX_SESSIONS=5
    volumes:
      - /dev/shm:/dev/shm # For Firefox performance
    links:
      - selenium-hub

  edge:
    image: selenium/node-edge:latest
    container_name: edge
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PORT=4442
      - SE_NODE_MAX_INSTANCES=2
      - SE_NODE_MAX_SESSIONS=5
    volumes:
      - /dev/shm:/dev/shm # For Edge performance
    links:
      - selenium-hub
